### ISSUE TITLE
Firmware build errors

### ISSUE THREAD

**Issue by mattuna15** [jamesbowman/gd3x-dazzler#1]
Just going through the firmware build for the Dazzler to get going with my own firmware. There's a number of errors which I'm not sure about.

The Verilator stage fails on duplicate definitions on these parameters: 
```
           output wire uart0_wr,
           output wire uart0_rd,
```

The file "xilinxmake" mentioned in the Makefile is missing from the repo. Would it be possible to get this file included?

Running the "./go" command produces this error.
```
make: Entering directory '/home/x/gd3x-dazzler/j1'
make: *** No rule to make target 'build/dazzler.hex'. Stop.
make: Leaving directory '/home/x/gd3x-dazzler/j1'
```

Also, would it be possible to get the .dazzler files for the main firmware and textmode as a release binary?

Posted in forum as well.

**Comment by mattuna15** [comment]
Hi thanks for the files.

We have this issue in verilator:

`verilator -Wall --cc -DVERILATOR=1 j1a.v ../../j1.v ../../stack2.v ../../hdmi.v --top-module j1a --exe # sim_main.cpp
%Error-PROCASSWIRE: j1a.v:31: Procedural assignment to wire, perhaps intended var (IEEE 1800-2017 6.5): 'insn'
                            : ... In instance j1a
    insn <= ram_prog[code_addr[12:0]];
    ^~~~
%Error-PROCASSWIRE: j1a.v:32: Procedural assignment to wire, perhaps intended var (IEEE 1800-2017 6.5): 'din'
                            : ... In instance j1a
    din <= ram_prog[mem_raddr[13:1]];
    ^~~
%Error: Exiting due to 2 error(s)
        ... See the manual and https://verilator.org for more assistance.
make: *** [Makefile:14: obj_dir/Vj1a__ALL.a] Error 1
`
and still get this error when running "go" in the source root

```
gd3x-dazzler$ ./go
make: Entering directory '/home/x/gd3x-dazzler/j1'
make: *** No rule to make target 'build/dazzler.hex'. Stop.
make: Leaving directory '/home/x/gd3x-dazzler/j1'
```

**Comment by mattuna15** [comment]
Also, once ISE kicks in (after disabling verilator and running manually)

```
Elaborating module <cpu>.

Elaborating module <bram_tdp(DATA=16,ADDR=13,INIT=1)>.
ERROR:HDLCompiler:990 - "/home/x/gd3x-dazzler/dazzler.v" Line 30: Cannot open file j1/build/base.hex
```

**Comment by mattuna15** [comment]
@jamesbowman thank you for the fixes. 
One last change: to the go file I had to change it to `make -C j1 build/bringup.hex`

Also - what is needed to create the image.dazzler to load via the boot menu? 
Is it just a case of renaming the the created "bin" files as image.dazzler? 

Really appreciate your help!

**Comment by mattuna15** [comment]
`make: Entering directory '/home/x/gd3x-dazzler/j1'
make: *** No rule to make target 'build/dazzler.hex'. Stop.
make: Leaving directory '/home/x/gd3x-dazzler/j1'
`

**Comment by jamesbowman** [comment]
Right, the Verilator failure prevents the system from building the file `j1/build/base.hex`.

I just tried building with Verilator stable (4.108). I fixed the above issues in my code, but now it fails to link because of some new change in Verilator behaviour.

Working on some fixes so that it can build with all the various Verilator versions now.

**Comment by jamesbowman** [comment]
@mattuna15 yes those "bin" files are slot images, you can use them as boot images.

**Comment by mattuna15** [comment]
> Right, the Verilator failure prevents the system from building the file `j1/build/base.hex`.
> 
> I just tried building with Verilator stable (4.108). I fixed the above issues in my code, but now it fails to link because of some new change in Verilator behaviour.
> 
> Working on some fixes so that it can build with all the various Verilator versions now.

I have version `Verilator 4.028 2020-02-06 rev v4.026-92-g890cecc1` which works ok with your code fixes.

**Comment by mattuna15** [comment]
> @mattuna15 yes those "bin" files are slot images, you can use them as boot images.

Have moved a bin file from the firmware directory to `image.dazzler` the boot menu does not load the file and claims that image.dazzler is not found. However, using the  downloaded asteroid.dazzler file works fine. Is there another stage after building the bin files in the firmware?

**Comment by mattuna15** [comment]
Hi @jamesbowman can confirm that this all works now - just loaded the textmode binary built using this process into a slot.
🙏 Happy for you to close this one.
